# https://docs.docker.com/compose/compose-file
web:
  restart: always
  build: . # build an image using the ./Dockerfile
  ports: 
    - "5000:5000"
  expose:
    - "5000"
  volumes:
    - .:/usr/src/app/
  environment:
    - FLASK_APP=manage.py
    - FLASK_DEBUG=0
    - SECRET_KEY # must be defined in the host env
    - APP_STAGE # this one too
  command: flask test

dynamodb:
  restart: always
  image: dwmkerr/dynamodb
  ports:
    - "8000:8000"
  expose:
    - "8000"