# https://docs.docker.com/compose/compose-file
web:
  restart: always
  build: . # build an image using the ./Dockerfile
  ports: 
    - "5000:5000"
  expose:
    - "5000"
  volumes:
    - .:/usr/src/app/
  env_file: .env_dev
  command: flask test