# https://docs.docker.com/compose/compose-file
version: '3'
services:
  web:
    restart: "no"
    build: . # build an image using the ./Dockerfile
    ports:
      - "5000:5000"
    expose:
      - "5000"
    volumes:
      - .:/usr/src/app/
    depends_on:
      - dynamodb
    environment:
      - FLASK_APP=manage.py
      - FLASK_DEBUG=0
      - DB_PING_LAZY=True # makes it possible to create an app when the expenses table is empty
      - AWS_DEFAULT_REGION=eu-central-1
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_ACCESS_KEY_ID=dummy
      - SECRET_KEY=dummy # must be defined in the host env
      - APP_STAGE=testing # this one too
      - LOCAL_DYNAMODB_URL=http://dynamodb:8000
    command: flask test

  dynamodb:
    restart: always
    image: dwmkerr/dynamodb
    ports:
      - "8000:8000"
    expose:
      - "8000"