# https://docs.docker.com/compose/compose-file
web:
  restart: always
  build: . # build an image using the ./Dockerfile
  ports: 
    - "5000:5000"
  expose:
    - "5000"
  volumes:
    - .:/usr/src/app/
  env_file: .env_dev
  command: flask test

dynamodb:
  restart: always
  image: dwmkerr/dynamodb
  ports:
    - "8000:8000"
  expose:
    - "8000"